namespace PrompterOne.Shared.Settings.Models;

public static class SettingsStreamingText
{
    public const string AddDistributionTargetButtonLabel = "SettingsStreamingAddDistributionTargetButtonLabel";
    public const string AddTransportConnectionButtonLabel = "SettingsStreamingAddTransportConnectionButtonLabel";
    public const string AvailableInProgramRoutingLabel = "SettingsStreamingAvailableInProgramRoutingLabel";
    public const string BaseUrlLabel = "SettingsStreamingBaseUrlLabel";
    public const string BitrateLabel = "SettingsStreamingBitrateLabel";
    public const string BlockedStatusLabel = "SettingsStreamingBlockedStatusLabel";
    public const string BoundTransportConnectionsLabel = "SettingsStreamingBoundTransportConnectionsLabel";
    public const string BoundTransportConnectionsSummary = "SettingsStreamingBoundTransportConnectionsSummary";
    public const string BoundTransportSelectedLabel = "SettingsStreamingBoundTransportSelectedLabel";
    public const string BoundTransportAvailableLabel = "SettingsStreamingBoundTransportAvailableLabel";
    public const string ConnectionRoleLabel = "SettingsStreamingConnectionRoleLabel";
    public const string ConnectionRoleBothLabel = "SettingsStreamingConnectionRoleBothLabel";
    public const string ConnectionRolePublishLabel = "SettingsStreamingConnectionRolePublishLabel";
    public const string ConnectionRoleSourceLabel = "SettingsStreamingConnectionRoleSourceLabel";
    public const string DestinationDisabledSummary = "SettingsStreamingDestinationDisabledSummary";
    public const string DestinationDisabledStatusLabel = "SettingsStreamingDestinationDisabledStatusLabel";
    public const string DestinationNeedsSetupStatusLabel = "SettingsStreamingDestinationNeedsSetupStatusLabel";
    public const string DestinationNoSourceSummary = "SettingsStreamingDestinationNoSourceSummary";
    public const string DestinationReadyStatusLabel = "SettingsStreamingDestinationReadyStatusLabel";
    public const string DestinationRelayStatusLabel = "SettingsStreamingDestinationRelayStatusLabel";
    public const string DistributionTargetsTitle = "SettingsStreamingDistributionTargetsTitle";
    public const string FullHd1080p30Label = "SettingsStreamingFullHd1080p30Label";
    public const string FullHd1080p60Label = "SettingsStreamingFullHd1080p60Label";
    public const string IncludeCameraInOutputLabel = "SettingsStreamingIncludeCameraInOutputLabel";
    public const string LocalDestinationSummaryFormat = "SettingsStreamingLocalDestinationSummaryFormat";
    public const string LocalRecordingTitle = "SettingsStreamingLocalRecordingTitle";
    public const string ProgramCaptureTitle = "SettingsStreamingProgramCaptureTitle";
    public const string OutputResolutionLabel = "SettingsStreamingOutputResolutionLabel";
    public const string PublishUrlLabel = "SettingsStreamingPublishUrlLabel";
    public const string RemoveDestinationLabel = "SettingsStreamingRemoveDestinationLabel";
    public const string RoomNameLabel = "SettingsStreamingRoomNameLabel";
    public const string RtmpUrlLabel = "SettingsStreamingRtmpUrlLabel";
    public const string ServerUrlLabel = "SettingsStreamingServerUrlLabel";
    public const string ShowTextOverlayLabel = "SettingsStreamingShowTextOverlayLabel";
    public const string SourcePickerSectionLabel = "SettingsStreamingSourcePickerSectionLabel";
    public const string SourcePickerNoCamerasSelectedLabel = "SettingsStreamingSourcePickerNoCamerasSelectedLabel";
    public const string SourcePickerSingleCameraSelectedFormat = "SettingsStreamingSourcePickerSingleCameraSelectedFormat";
    public const string SourcePickerMultipleCamerasSelectedFormat = "SettingsStreamingSourcePickerMultipleCamerasSelectedFormat";
    public const string SourcePickerEmptyStateMessage = "SettingsStreamingSourcePickerEmptyStateMessage";
    public const string SourcePickerSelectedLabel = "SettingsStreamingSourcePickerSelectedLabel";
    public const string SourcePickerAvailableLabel = "SettingsStreamingSourcePickerAvailableLabel";
    public const string StreamKeyLabel = "SettingsStreamingStreamKeyLabel";
    public const string TargetNameLabel = "SettingsStreamingTargetNameLabel";
    public const string TokenLabel = "SettingsStreamingTokenLabel";
    public const string TransportConnectionsTitle = "SettingsStreamingTransportConnectionsTitle";
    public const string UltraHd2160p30Label = "SettingsStreamingUltraHd2160p30Label";
    public const string UnsupportedTransportSummary = "SettingsStreamingUnsupportedTransportSummary";
    public const string ViewUrlLabel = "SettingsStreamingViewUrlLabel";
    public const string Hd720p30Label = "SettingsStreamingHd720p30Label";
}
